---
- name: "Prepare proxy URL for username and password if needed."
  set_fact:
    apt_proxy_server_enhanced: "{{ apt_proxy_server if (apt_proxy_username == '' or apt_proxy_password == '') else apt_proxy_username + '@' + apt_proxy_password + ':' + apt_proxy_server }}"

- name: "Configure Proxy for APT."
  template:
   dest: /etc/apt/apt.conf.d/99proxy
   src: 99proxy.j2
   owner: root
   group: root
   mode: 0644
  when: apt_proxy_server != ""

- name: "Remove proxy for APT."
  file:
    path: '/etc/apt/apt.conf.d/99proxy'
    state: absent
  when: apt_proxy_server == "" or apt_proxy_port == ""
